export const DefaultMainMenuItems = {
  menuItems: {
    'default.home': {
      title: 'Home',
      titleKey: 'menuItem.home',
      icon: 'home',
      to: '/',
      priority: 100,
    },
    'default.my-group': {
      title: 'My Group',
      titleKey: 'menuItem.myGroup',
      icon: 'group',
      priority: 90,
    },
    'default.catalog': {
      title: 'Catalog',
      titleKey: 'menuItem.catalog',
      icon: 'category',
      to: 'catalog',
      priority: 80,
    },
    'default.apis': {
      title: 'APIs',
      titleKey: 'menuItem.apis',
      icon: 'extension',
      to: 'api-docs',
      priority: 70,
    },
    'default.learning-path': {
      title: 'Learning Paths',
      titleKey: 'menuItem.learningPaths',
      icon: 'school',
      to: 'learning-paths',
      priority: 60,
    },
    'default.kuadrant': {
      title: 'Kuadrant',
      icon: 'extension',
      priority: 55,
    },
    'default.kuadrant.api-products': {
      title: 'API Products',
      icon: 'storefront',
      to: 'kuadrant/api-products',
      parent: 'default.kuadrant',
      priority: 20,
    },
    'default.kuadrant.api-keys': {
      title: 'API Keys',
      icon: 'security',
      to: 'kuadrant/api-keys',
      parent: 'default.kuadrant',
      priority: 10,
    },
    'default.create': {
      title: 'Self-service',
      titleKey: 'menuItem.selfService',
      icon: 'add',
      to: 'create',
      priority: 50,
    },
    'default.admin.rbac': {
      title: 'RBAC',
      icon: 'admin',
      to: 'rbac',
      priority: 10,
    },
  },
};
